---
- hosts: all
  become: yes
  become_method: sudo

  roles:
    - role: common
    # We use the built-in MySQL fulltext search by default.
    # - role: install_solr
    - role: setup_mysql
    - role: setup_apache
