---
- name: Create default MySQL application database
  mysql_db:
    name: "{{ mysql_database }}"

- name: Create default MySQL application user
  mysql_user:
    name: "{{ mysql_username }}"
    password: "{{ mysql_password }}"
    host: localhost
    priv: "{{ mysql_database }}.*:ALL"
